# Links Electric car share analysis

## Importing libraries

In [123]:
# importing numpy library
import numpy as np

# importing pandas library
import pandas as pd

## Loading the data set

Autolib_dataset(2).csv [LINK] (http://bit.ly/autolib_dataset)

In [124]:
#Loading the dataset and previewing
autolib = pd.read_csv("Autolib_dataset (2).csv")
autolib

,Address,Cars,Bluecar counter,Utilib counter,Utilib 1.4 counter,Charge Slots,Charging Status,City,Displayed comment,ID,...,Scheduled at,Slots,Station type,Status,Subscription status,year,month,day,hour,minute
0,2 Avenue de Suffren,0,0,0,0,0,nonexistent,Paris,NaN,paris-suffren-2,...,NaN,2,station,ok,nonexistent,2018,4,8,11,43
1,145 Rue Raymond Losserand,6,6,0,0,0,operational,Paris,NaN,paris-raymondlosserand-145,...,NaN,0,station,ok,nonexistent,2018,4,6,7,24
2,2 Avenue John Fitzgerald Kennedy,3,3,0,2,0,operational,Le Bourget,NaN,lebourget-johnfitzgeraldkennedy-2,...,NaN,1,station,ok,nonexistent,2018,4,3,20,14
3,51 Rue EugÃ¨ne OudinÃ©,3,3,1,0,1,operational,Paris,NaN,paris-eugeneoudine-51,...,NaN,2,station,ok,nonexistent,2018,4,4,4,37
4,6 avenue de la Porte de Champerret,3,3,0,0,0,nonexistent,Paris,NaN,paris-portedechamperret-6,...,NaN,3,station,ok,nonexistent,2018,4,8,17,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,8 avenue MÃ©nelotte,2,2,0,0,0,nonexistent,Colombes,NaN,colombes-menelotte-8,...,NaN,3,station,ok,nonexistent,2018,4,6,11,26
4996,37 rue de Dantzig,4,4,0,0,1,operational,Paris,NaN,paris-dantzig-37,...,NaN,2,station,ok,nonexistent,2018,4,4,16,56
4997,142 rue du Bac,1,1,0,0,1,operational,Paris,NaN,paris-bac-142,...,NaN,4,station,ok,nonexistent,2018,4,1,7,1
4998,2 avenue du Val de Fontenay,2,2,0,0,0,nonexistent,Fontenay-Sous-Bois,NaN,fontenaysousbois-valdefontenay-2,...,NaN,3,station,ok,nonexistent,2018,4,4,17,27
4999,5 Rue Henry Brisson,4,4,0,0,0,operational,Paris,NaN,paris-henrybrisson-5,...,NaN,0,station,ok,nonexistent,2018,4,8,10,2

## previewing the first ten columns of the dataset

In [125]:
autolib.head(10)

,Address,Cars,Bluecar counter,Utilib counter,Utilib 1.4 counter,Charge Slots,Charging Status,City,Displayed comment,ID,...,Scheduled at,Slots,Station type,Status,Subscription status,year,month,day,hour,minute
0,2 Avenue de Suffren,0,0,0,0,0,nonexistent,Paris,NaN,paris-suffren-2,...,NaN,2,station,ok,nonexistent,2018,4,8,11,43
1,145 Rue Raymond Losserand,6,6,0,0,0,operational,Paris,NaN,paris-raymondlosserand-145,...,NaN,0,station,ok,nonexistent,2018,4,6,7,24
2,2 Avenue John Fitzgerald Kennedy,3,3,0,2,0,operational,Le Bourget,NaN,lebourget-johnfitzgeraldkennedy-2,...,NaN,1,station,ok,nonexistent,2018,4,3,20,14
3,51 Rue EugÃ¨ne OudinÃ©,3,3,1,0,1,operational,Paris,NaN,paris-eugeneoudine-51,...,NaN,2,station,ok,nonexistent,2018,4,4,4,37
4,6 avenue de la Porte de Champerret,3,3,0,0,0,nonexistent,Paris,NaN,paris-portedechamperret-6,...,NaN,3,station,ok,nonexistent,2018,4,8,17,23
5,8 Boulevard Voltaire,0,0,0,0,0,nonexistent,Paris,NaN,paris-voltaire-8,...,NaN,4,station,ok,nonexistent,2018,4,6,7,2
6,37 rue Leblanc,0,0,0,0,0,nonexistent,Paris,"Station en parking (niv -1), accÃ¨s 37 rue Leb...",paris-citroencevennes-parking,...,NaN,0,station,closed,nonexistent,2018,4,8,18,20
7,17 Rue des Luaps ProlongÃ©e,3,3,1,0,0,nonexistent,Nanterre,NaN,nanterre-luaps-17,...,NaN,0,station,ok,nonexistent,2018,4,4,22,13
8,34 avenue Jean Moulin,1,1,0,0,0,nonexistent,Paris,NaN,paris-jeanmoulin-34,...,NaN,4,station,ok,nonexistent,2018,4,2,22,58
9,41 boulevard de Rochechouart,6,6,0,0,0,nonexistent,Paris,NaN,paris-anvers-parking,...,NaN,0,station,ok,nonexistent,2018,4,4,15,2

## Accessing information about the dataset

In [126]:
# viewing the columns in the data set
autolib.columns

Index(['Address', 'Cars', 'Bluecar counter', 'Utilib counter',
       'Utilib 1.4 counter', 'Charge Slots', 'Charging Status', 'City',
       'Displayed comment', 'ID', 'Kind', 'Geo point', 'Postal code',
       'Public name', 'Rental status', 'Scheduled at', 'Slots', 'Station type',
       'Status', 'Subscription status', 'year', 'month', 'day', 'hour',
       'minute'],
      dtype='object')

## Finding the number of columns rows and columns

In [127]:
print(autolib.shape)

(5000, 25)

## checking the data type for the dataset

In [128]:
autolib.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Address              5000 non-null   object
 1   Cars                 5000 non-null   int64
 2   Bluecar counter      5000 non-null   int64
 3   Utilib counter       5000 non-null   int64
 4   Utilib 1.4 counter   5000 non-null   int64
 5   Charge Slots         5000 non-null   int64
 6   Charging Status      5000 non-null   object
 7   City                 5000 non-null   object
 8   Displayed comment    111 non-null    object
 9   ID                   5000 non-null   object
 10  Kind                 5000 non-null   object
 11  Geo point            5000 non-null   object
 12  Postal code          5000 non-null   int64
 13  Public name          5000 non-null   object
 14  Rental status        5000 non-null   object
 15  Scheduled at         47 non-null     object
 16  Slots                5000 non-null   int64
 17  Station type         5000 non-null   object
 18  Status               5000 non-null   object
 19  Subscription status  5000 non-null   object
 20  year                 5000 non-null   int64
 21  month                5000 non-null   int64
 22  day                  5000 non-null   int64
 23  hour                 5000 non-null   int64
 24  minute               5000 non-null   int64
dtypes: int64(12), object(13)
memory usage: 976.7+ KB

## Cleaning the dataset

# Finding and counting missing data

#### To count non-missing values in the data set

In [129]:
# since the data has 5000 rows the columns with less than 5000 implies there are missing values
autolib.count()

Address                5000
Cars                   5000
Bluecar counter        5000
Utilib counter         5000
Utilib 1.4 counter     5000
Charge Slots           5000
Charging Status        5000
City                   5000
Displayed comment       111
ID                     5000
Kind                   5000
Geo point              5000
Postal code            5000
Public name            5000
Rental status          5000
Scheduled at             47
Slots                  5000
Station type           5000
Status                 5000
Subscription status    5000
year                   5000
month                  5000
day                    5000
hour                   5000
minute                 5000
dtype: int64

#### To determine the numebr of missing values

In [130]:
num_rows = autolib.shape[0]
num_missing = num_rows - autolib.count() 
num_missing

Address                   0
Cars                      0
Bluecar counter           0
Utilib counter            0
Utilib 1.4 counter        0
Charge Slots              0
Charging Status           0
City                      0
Displayed comment      4889
ID                        0
Kind                      0
Geo point                 0
Postal code               0
Public name               0
Rental status             0
Scheduled at           4953
Slots                     0
Station type              0
Status                    0
Subscription status       0
year                      0
month                     0
day                       0
hour                      0
minute                    0
dtype: int64

#### dropping the columns conataining the missing values in the data  set

In [131]:
auto_1 = autolib.drop(["Displayed comment", "Scheduled at"], axis = 1) #dropping the Displyed comment column
auto_1

,Address,Cars,Bluecar counter,Utilib counter,Utilib 1.4 counter,Charge Slots,Charging Status,City,ID,Kind,...,Rental status,Slots,Station type,Status,Subscription status,year,month,day,hour,minute
0,2 Avenue de Suffren,0,0,0,0,0,nonexistent,Paris,paris-suffren-2,STATION,...,operational,2,station,ok,nonexistent,2018,4,8,11,43
1,145 Rue Raymond Losserand,6,6,0,0,0,operational,Paris,paris-raymondlosserand-145,STATION,...,operational,0,station,ok,nonexistent,2018,4,6,7,24
2,2 Avenue John Fitzgerald Kennedy,3,3,0,2,0,operational,Le Bourget,lebourget-johnfitzgeraldkennedy-2,STATION,...,operational,1,station,ok,nonexistent,2018,4,3,20,14
3,51 Rue EugÃ¨ne OudinÃ©,3,3,1,0,1,operational,Paris,paris-eugeneoudine-51,STATION,...,operational,2,station,ok,nonexistent,2018,4,4,4,37
4,6 avenue de la Porte de Champerret,3,3,0,0,0,nonexistent,Paris,paris-portedechamperret-6,PARKING,...,operational,3,station,ok,nonexistent,2018,4,8,17,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,8 avenue MÃ©nelotte,2,2,0,0,0,nonexistent,Colombes,colombes-menelotte-8,STATION,...,operational,3,station,ok,nonexistent,2018,4,6,11,26
4996,37 rue de Dantzig,4,4,0,0,1,operational,Paris,paris-dantzig-37,STATION,...,operational,2,station,ok,nonexistent,2018,4,4,16,56
4997,142 rue du Bac,1,1,0,0,1,operational,Paris,paris-bac-142,STATION,...,operational,4,station,ok,nonexistent,2018,4,1,7,1
4998,2 avenue du Val de Fontenay,2,2,0,0,0,nonexistent,Fontenay-Sous-Bois,fontenaysousbois-valdefontenay-2,STATION,...,operational,3,station,ok,nonexistent,2018,4,4,17,27
4999,5 Rue Henry Brisson,4,4,0,0,0,operational,Paris,paris-henrybrisson-5,STATION,...,operational,0,station,ok,nonexistent,2018,4,8,10,2

#### Confirming the number of columns of the cleaned data set

In [132]:
auto_1.shape

(5000, 23)

#### Checking if there are any nul values

In [133]:
auto_1.count()

Address                5000
Cars                   5000
Bluecar counter        5000
Utilib counter         5000
Utilib 1.4 counter     5000
Charge Slots           5000
Charging Status        5000
City                   5000
ID                     5000
Kind                   5000
Geo point              5000
Postal code            5000
Public name            5000
Rental status          5000
Slots                  5000
Station type           5000
Status                 5000
Subscription status    5000
year                   5000
month                  5000
day                    5000
hour                   5000
minute                 5000
dtype: int64

#### Formating the column heads

In [134]:
auto_1.columns = ['Address', 'Cars', 'Bluecar_counter', 'Utilib_counter',
       'Utilib_1.4_counter', 'Charge_Slots', 'Charging_Status', 'City',
       'ID', 'Kind', 'Geo_point', 'Postal_code',
       'Public_name', 'Rental_status',  'Slots', 'Station_type',
       'Status', 'Subscription_status', 'year', 'month', 'day', 'hour',
       'minute']

In [135]:
# confirming that the column head are riightly formatted
auto_1.columns

Index(['Address', 'Cars', 'Bluecar_counter', 'Utilib_counter',
       'Utilib_1.4_counter', 'Charge_Slots', 'Charging_Status', 'City', 'ID',
       'Kind', 'Geo_point', 'Postal_code', 'Public_name', 'Rental_status',
       'Slots', 'Station_type', 'Status', 'Subscription_status', 'year',
       'month', 'day', 'hour', 'minute'],
      dtype='object')

## Analysis

#### Identify the most popular hour of the day for picking up a shared electric car (Bluecar) in the city of Paris over the month of April 2018.

#### checking the data type for the variables

In [136]:
auto_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Address              5000 non-null   object
 1   Cars                 5000 non-null   int64
 2   Bluecar_counter      5000 non-null   int64
 3   Utilib_counter       5000 non-null   int64
 4   Utilib_1.4_counter   5000 non-null   int64
 5   Charge_Slots         5000 non-null   int64
 6   Charging_Status      5000 non-null   object
 7   City                 5000 non-null   object
 8   ID                   5000 non-null   object
 9   Kind                 5000 non-null   object
 10  Geo_point            5000 non-null   object
 11  Postal_code          5000 non-null   int64
 12  Public_name          5000 non-null   object
 13  Rental_status        5000 non-null   object
 14  Slots                5000 non-null   int64
 15  Station_type         5000 non-null   object
 16  Status               5000 non-null   object
 17  Subscription_status  5000 non-null   object
 18  year                 5000 non-null   int64
 19  month                5000 non-null   int64
 20  day                  5000 non-null   int64
 21  hour                 5000 non-null   int64
 22  minute               5000 non-null   int64
dtypes: int64(12), object(11)
memory usage: 898.6+ KB

#### converting the year,month,day,hour,minute to string

In [137]:
#auto_1[["year","month","day","hour", "minute"]].astype("object") 
#df[["a", "b"]] = df[["a", "b"]].apply(pd.to_numeric)
auto_1.year = auto_1.year.astype(str)
auto_1.month = auto_1.month.astype(str)
auto_1.day = auto_1.day.astype(str)
auto_1.hour = auto_1.hour.astype(str)
auto_1.minute = auto_1.minute.astype(str)

#### Confirming that the data type for the five columns has been changed

In [138]:
auto_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Address              5000 non-null   object
 1   Cars                 5000 non-null   int64
 2   Bluecar_counter      5000 non-null   int64
 3   Utilib_counter       5000 non-null   int64
 4   Utilib_1.4_counter   5000 non-null   int64
 5   Charge_Slots         5000 non-null   int64
 6   Charging_Status      5000 non-null   object
 7   City                 5000 non-null   object
 8   ID                   5000 non-null   object
 9   Kind                 5000 non-null   object
 10  Geo_point            5000 non-null   object
 11  Postal_code          5000 non-null   int64
 12  Public_name          5000 non-null   object
 13  Rental_status        5000 non-null   object
 14  Slots                5000 non-null   int64
 15  Station_type         5000 non-null   object
 16  Status               5000 non-null   object
 17  Subscription_status  5000 non-null   object
 18  year                 5000 non-null   object
 19  month                5000 non-null   object
 20  day                  5000 non-null   object
 21  hour                 5000 non-null   object
 22  minute               5000 non-null   object
dtypes: int64(7), object(16)
memory usage: 898.6+ KB

#### Converting the year,month,day,hour and minute into one

In [139]:
auto_1['date'] = auto_1['year'] + ':' + auto_1['month'] + ':' + auto_1['day'] + ':' + auto_1['hour'] + ':' + auto_1['minute']
#df['date'] = df['year'] + '-' +nex

#### Displaying the data after converting

In [140]:
auto_1

,Address,Cars,Bluecar_counter,Utilib_counter,Utilib_1.4_counter,Charge_Slots,Charging_Status,City,ID,Kind,...,Slots,Station_type,Status,Subscription_status,year,month,day,hour,minute,date
0,2 Avenue de Suffren,0,0,0,0,0,nonexistent,Paris,paris-suffren-2,STATION,...,2,station,ok,nonexistent,2018,4,8,11,43,2018:4:8:11:43
1,145 Rue Raymond Losserand,6,6,0,0,0,operational,Paris,paris-raymondlosserand-145,STATION,...,0,station,ok,nonexistent,2018,4,6,7,24,2018:4:6:7:24
2,2 Avenue John Fitzgerald Kennedy,3,3,0,2,0,operational,Le Bourget,lebourget-johnfitzgeraldkennedy-2,STATION,...,1,station,ok,nonexistent,2018,4,3,20,14,2018:4:3:20:14
3,51 Rue EugÃ¨ne OudinÃ©,3,3,1,0,1,operational,Paris,paris-eugeneoudine-51,STATION,...,2,station,ok,nonexistent,2018,4,4,4,37,2018:4:4:4:37
4,6 avenue de la Porte de Champerret,3,3,0,0,0,nonexistent,Paris,paris-portedechamperret-6,PARKING,...,3,station,ok,nonexistent,2018,4,8,17,23,2018:4:8:17:23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,8 avenue MÃ©nelotte,2,2,0,0,0,nonexistent,Colombes,colombes-menelotte-8,STATION,...,3,station,ok,nonexistent,2018,4,6,11,26,2018:4:6:11:26
4996,37 rue de Dantzig,4,4,0,0,1,operational,Paris,paris-dantzig-37,STATION,...,2,station,ok,nonexistent,2018,4,4,16,56,2018:4:4:16:56
4997,142 rue du Bac,1,1,0,0,1,operational,Paris,paris-bac-142,STATION,...,4,station,ok,nonexistent,2018,4,1,7,1,2018:4:1:7:1
4998,2 avenue du Val de Fontenay,2,2,0,0,0,nonexistent,Fontenay-Sous-Bois,fontenaysousbois-valdefontenay-2,STATION,...,3,station,ok,nonexistent,2018,4,4,17,27,2018:4:4:17:27
4999,5 Rue Henry Brisson,4,4,0,0,0,operational,Paris,paris-henrybrisson-5,STATION,...,0,station,ok,nonexistent,2018,4,8,10,2,2018:4:8:10:2

In [141]:
sorted_auto =auto_1.sort_values(by=['date'], ascending = False)
sorted_auto

,Address,Cars,Bluecar_counter,Utilib_counter,Utilib_1.4_counter,Charge_Slots,Charging_Status,City,ID,Kind,...,Slots,Station_type,Status,Subscription_status,year,month,day,hour,minute,date
631,5 Rue Henry Brisson,4,4,0,1,0,operational,Paris,paris-henrybrisson-5,STATION,...,0,station,ok,nonexistent,2018,4,9,9,6,2018:4:9:9:6
2457,162 rue Championnet,3,3,0,0,1,operational,Paris,paris-championnet-162,STATION,...,3,station,ok,nonexistent,2018,4,9,9,59,2018:4:9:9:59
4606,4 rue Pouchet,0,0,0,0,1,operational,Paris,paris-pouchet-4,STATION,...,5,station,ok,nonexistent,2018,4,9,9,58,2018:4:9:9:58
2376,245 boulevard Jean JaurÃ¨s,3,3,1,0,0,nonexistent,Boulogne-Billancourt,boulognebillancourt-jeanjaures-245,STATION,...,0,station,ok,nonexistent,2018,4,9,9,57,2018:4:9:9:57
4140,105 Rue de Rennes,0,0,0,0,0,nonexistent,Paris,paris-rennes-105,STATION,...,4,station,ok,nonexistent,2018,4,9,9,51,2018:4:9:9:51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3400,168 boulevard du GÃ©nÃ©ral de Gaulle,5,5,0,0,0,nonexistent,Garches,garches-degaulle-168,STATION,...,1,station,ok,operational,2018,4,1,0,16,2018:4:1:0:16
3535,8 rue Goubet,3,3,0,0,0,operational,Paris,paris-goubet-8,STATION,...,3,station,ok,nonexistent,2018,4,1,0,11,2018:4:1:0:11
3652,7 rue Raymond Pitet,4,4,0,0,0,operational,Paris,paris-raymondpitet-7,STATION,...,1,station,ok,nonexistent,2018,4,1,0,11,2018:4:1:0:11
4357,11 rue Marguerite Long,3,3,0,0,0,operational,Paris,paris-margueritelong-11,STATION,...,3,station,ok,nonexistent,2018,4,1,0,10,2018:4:1:0:10
1046,112 Rue Monge BÃ¢timent Lieu-dit,0,0,0,0,0,nonexistent,Paris,paris-monge-112,STATION,...,4,station,ok,nonexistent,2018,4,1,0,0,2018:4:1:0:0

In [142]:
sorted_auto['Electric_usage_in_Bluecar'] = sorted_auto['Bluecar_counter'].diff()
sorted_auto

,Address,Cars,Bluecar_counter,Utilib_counter,Utilib_1.4_counter,Charge_Slots,Charging_Status,City,ID,Kind,...,Station_type,Status,Subscription_status,year,month,day,hour,minute,date,Electric_usage_in_Bluecar
631,5 Rue Henry Brisson,4,4,0,1,0,operational,Paris,paris-henrybrisson-5,STATION,...,station,ok,nonexistent,2018,4,9,9,6,2018:4:9:9:6,NaN
2457,162 rue Championnet,3,3,0,0,1,operational,Paris,paris-championnet-162,STATION,...,station,ok,nonexistent,2018,4,9,9,59,2018:4:9:9:59,-1.0
4606,4 rue Pouchet,0,0,0,0,1,operational,Paris,paris-pouchet-4,STATION,...,station,ok,nonexistent,2018,4,9,9,58,2018:4:9:9:58,-3.0
2376,245 boulevard Jean JaurÃ¨s,3,3,1,0,0,nonexistent,Boulogne-Billancourt,boulognebillancourt-jeanjaures-245,STATION,...,station,ok,nonexistent,2018,4,9,9,57,2018:4:9:9:57,3.0
4140,105 Rue de Rennes,0,0,0,0,0,nonexistent,Paris,paris-rennes-105,STATION,...,station,ok,nonexistent,2018,4,9,9,51,2018:4:9:9:51,-3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3400,168 boulevard du GÃ©nÃ©ral de Gaulle,5,5,0,0,0,nonexistent,Garches,garches-degaulle-168,STATION,...,station,ok,operational,2018,4,1,0,16,2018:4:1:0:16,2.0
3535,8 rue Goubet,3,3,0,0,0,operational,Paris,paris-goubet-8,STATION,...,station,ok,nonexistent,2018,4,1,0,11,2018:4:1:0:11,-2.0
3652,7 rue Raymond Pitet,4,4,0,0,0,operational,Paris,paris-raymondpitet-7,STATION,...,station,ok,nonexistent,2018,4,1,0,11,2018:4:1:0:11,1.0
4357,11 rue Marguerite Long,3,3,0,0,0,operational,Paris,paris-margueritelong-11,STATION,...,station,ok,nonexistent,2018,4,1,0,10,2018:4:1:0:10,-1.0
1046,112 Rue Monge BÃ¢timent Lieu-dit,0,0,0,0,0,nonexistent,Paris,paris-monge-112,STATION,...,station,ok,nonexistent,2018,4,1,0,0,2018:4:1:0:0,-3.0

In [147]:
[(sorted_auto.City == "Paris") & (sorted_auto.Electric_usage_in_Bluecar < 0)].groupby('hour')['hour'].count().head(1)

AttributeError: 'list' object has no attribute 'groupby'

####  What postal code is most popular for picking blue care?

In [146]:
auto_1.loc[auto_1["Bluecar_counter"] > 0 , "Postal_code"].mode() # the most popular postal code picking bluecar counter is 75015

0    75015
dtype: int64

#### The most popular station

In [ ]:
#What station is the most popular?
auto_1.Public_name.value_counts() # Paris/Porte de Montrouge/8 is the most popular

In [145]:
auto_1.loc[auto_1["Postal_code"]==  75015, "Public_name" ].iloc[0]# the most popular station does not belong to the postal code that is famous for picking blue car

'Paris/Suffren/2'

#### What is the most popular hour for returning cars?

In [144]:
auto_1.hour.value_counts().head(1) # 21 is the most popular hour

21    237
Name: hour, dtype: int64